### ISSUE TITLE
Image display problem

### ISSUE THREAD

**Issue by ousinkou** [tedchao/ColorfulCurves#2]
When I loaded image, this problem occurred
![image](https://github.com/tedchao/ColorfulCurves/assets/13220463/b42627ef-5e8f-4ff1-87d4-1aeb3fd578bb)
What's going on?

**Comment by ousinkou** [comment]
It's problem of lab2rgb_LUT_opencl function

**Comment by tedchao** [comment]
Hi,

Are you loading a .png or .jpeg image?

Ted

**Comment by ousinkou** [comment]
Yes, .png or .jpeg image all has this problem.After I replace lab2rgb_LUT_opencl function with color.lab2rgb,  problem seems solved.

**Comment by yig** [comment]
Nothing calls `lab2rgb_LUT_opencl()` directly. It overrides `lab2rgb_fast` at the bottom of `utils.py` if the OpenCL module successfully loads. You could comment out the assignment there.

**Comment by ousinkou** [comment]
@yig Yes, that's what I mean.
